name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^7.3.0
  http: ^0.13.3
  flutter_spinkit: ^5.0.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.1.0
  mocktail: ^0.1.4

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900